name: InfiniteJump
description: Jump to infinity!
main: zsallazar\infinitejump\InfiniteJump
src-namespace-prefix: zsallazar\infinitejump
version: 0.0.1
api: 5.0.0
author: zSALLAZAR

permissions:
  infinitejump.command:
    default: true