name: InfiniteJump
description:
main: zsallazar\infinitejump\InfiniteJump
src-namespace-prefix: zsallazar\infinitejump
version: 0.0.1
api: 5.0.0
author: zSALLAZAR

permissions:
  ffa.command:
    default: true