name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: PHPStan analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.3"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: 5

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze